upload_to_testflight:
  stage: deploy
  tags: [macos-andy]
  script:
    - fvm install
    - fvm flutter pub get
    - cd ios/fastlane
    - bundle install --quiet
    - mkdir Private
    - echo "$PASSPHRASE" > Private/passphrase
    - bundle exec fastlane beta
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      when: always 
    - when: manual

upload_prod_to_testflight:
  stage: deploy
  tags: [macos-andy]
  script:
    - fvm install
    - fvm exec dart pub global activate melos
    - fvm exec melos bootstrap --scope app --scope common
    - cd ios/fastlane
    - mkdir Private
    - echo "$PASSPHRASE" > Private/passphrase
    - bundle install --quiet
    - bundle exec fastlane beta_prod
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      when: always 
    - when: manual

upload_agent_to_testflight:
  stage: deploy
  tags: [macos-andy]
  script:
    - fvm install
    - fvm exec dart pub global activate melos
    - fvm exec melos bootstrap --scope app --scope common
    - cd ios/fastlane
    - bundle install --quiet
    - mkdir Private
    - echo "$PASSPHRASE" > Private/passphrase
    - bundle exec fastlane beta_agent
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      when: always 
    - when: manual